service: meetinger

package:
  individually: true
  exclude:
   - ./**

custom:
  mainTableArn: ${ssm:/dynamodb/${self:service}/${self:provider.stage}/main_table_arn~true}
  mainTableName: ${ssm:/dynamodb/${self:service}/${self:provider.stage}/main_table_name~true}
  webpack:
    packager: yarn
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
  serverless-iam-roles-per-function:
    defaultInherit: true
  prune:
    automatic: true
    number: 3
  <<: &authorizer
    name: AuthorizeUser
    managedExternally: false
    resultTtlInSeconds: 300
    identitySource: method.request.header.Authorization
    identityValidationExpression: ^Bearer [-0-9a-zA-Z\._]*$
    type: token

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, 'eu-central-1'}
  stage: ${opt:stage, 'dev'}

  apiGateway:
    shouldStartNameWithService: true

  logs:
    websocket:
      level: INFO

  tracing:
    apiGateway: true
    lambda: true

  stackTags:
    Service: ${self:service}
    Stage: ${self:provider.stage}
    Region: ${self:provider.region}
    Version: ${file(./package.json):version}
    Project: meetinger

  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - ${self:custom.mainTableArn}
        - Fn::Join:
          - "/"
          -
            - ${self:custom.mainTableArn}
            - "index/*"


functions:
  AuthorizeUser:
    handler: src/modules/users/usecase/authorizeUser/index.handler
    environment:
      ISS: ${ssm:/cognito-user-pool/${self:service}/${self:provider.stage}/iss~true}

  UserRegister:
    handler: src/modules/users/usecase/createUser/index.handler
    environment:
      MAIN_TABLE_NAME: ${self:custom.mainTableName}
    events:
      - cognitoUserPool:
          pool: ${self:service}_user_pool_${self:provider.stage}
          trigger: PostConfirmation
          existing: true

  WebsocketConnect:
    handler: src/modules/connection/usecase/createConnection/index.handler
    events:
      - websocket: 
          route: $connect
          authorizer: 
            name: AuthorizeUser
            identitySource:
              - 'route.request.querystring.Auth'
    environment:
      MAIN_TABLE_NAME: ${self:custom.mainTableName}
  
  WebsocketDisconnect:
    handler: src/modules/connection/usecase/deleteConnection/index.handler
    events:
      - websocket: 
          route: $disconnect
    environment:
      MAIN_TABLE_NAME: ${self:custom.mainTableName}

  CreateMeeting:
    handler: src/modules/meetings/usecase/createMeeting/index.handler
    environment:
      MAIN_TABLE_NAME: ${self:custom.mainTableName}
      EVENT_MEETING_CREATED_ARN: ${ssm:/sns/${self:service}/${self:provider.stage}/MeetingCreated_arn~true}
      EVENT_ATTENDEE_JOINED_ARN: ${ssm:/sns/${self:service}/${self:provider.stage}/AttendeeJoined_arn~true}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sns:Publish
        Resource: ${ssm:/sns/${self:service}/${self:provider.stage}/MeetingCreated_arn~true}
      - Effect: Allow
        Action:
          - sns:Publish
        Resource: ${ssm:/sns/${self:service}/${self:provider.stage}/AttendeeJoined_arn~true}
    events:
      - http:
          path: meetings
          method: post
          authorizer: *authorizer
  
  EditMeeting:
    handler: src/modules/meetings/usecase/editMeeting/index.handler
    environment:
      MAIN_TABLE_NAME: ${self:custom.mainTableName}
      EVENT_MEETING_CHANGED_ARN: ${ssm:/sns/${self:service}/${self:provider.stage}/MeetingChanged_arn~true}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sns:Publish
        Resource: ${ssm:/sns/${self:service}/${self:provider.stage}/MeetingChanged_arn~true}
    events:
      - http:
          path: meetings/{id}
          method: put
          authorizer: *authorizer
  
  JoinMeeting:
    handler: src/modules/meetings/usecase/joinMeeting/index.handler
    environment:
      MAIN_TABLE_NAME: ${self:custom.mainTableName}
      EVENT_ATTENDEE_JOINED_ARN: ${ssm:/sns/${self:service}/${self:provider.stage}/AttendeeJoined_arn~true}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sns:Publish
        Resource: ${ssm:/sns/${self:service}/${self:provider.stage}/AttendeeJoined_arn~true}
    events:
      - http:
          path: meetings/{id}/attendance
          method: post
          authorizer: *authorizer
  
  LeaveMeeting:
    handler: src/modules/meetings/usecase/leaveMeeting/index.handler
    environment:
      MAIN_TABLE_NAME: ${self:custom.mainTableName}
      EVENT_ATTENDEE_LEFT_ARN: ${ssm:/sns/${self:service}/${self:provider.stage}/AttendeeLeft_arn~true}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sns:Publish
        Resource: ${ssm:/sns/${self:service}/${self:provider.stage}/AttendeeLeft_arn~true}
    events:
      - http:
          path: meetings/{id}/attendance
          method: delete
          authorizer: *authorizer
  
  GetMeeting:
    handler: src/modules/meetings/usecase/getMeeting/index.handler
    environment:
      MAIN_TABLE_NAME: ${self:custom.mainTableName}
    events:
      - http:
          path: meetings/{id}
          method: get
          authorizer: *authorizer
  
  ListMeetings:
    handler: src/modules/meetings/usecase/listMeetings/index.handler
    environment:
      MAIN_TABLE_NAME: ${self:custom.mainTableName}
    events:
      - http:
          path: meetings
          method: get
  
  ListRegisteredMeetings:
    handler: src/modules/meetings/usecase/listRegisteredMeetings/index.handler
    environment:
      MAIN_TABLE_NAME: ${self:custom.mainTableName}
    events:
      - http:
          path: registered_meetings
          method: get
          authorizer: *authorizer

  GetAttendance:
    handler: src/modules/meetings/usecase/getAttendance/index.handler
    environment:
      MAIN_TABLE_NAME: ${self:custom.mainTableName}
    events:
      - http:
          path: meetings/{id}/attendance
          method: get
          authorizer: *authorizer

  PersistAttendee:
    handler: src/modules/meetings/usecase/persistAttendee/index.handler
    environment:
      MAIN_TABLE_NAME: ${self:custom.mainTableName}
    events:
      - sns: ${ssm:/sns/${self:service}/${self:provider.stage}/AttendeeJoined_arn~true}
  
  RemoveAttendee:
    handler: src/modules/meetings/usecase/removeAttendee/index.handler
    environment:
      MAIN_TABLE_NAME: ${self:custom.mainTableName}
    events:
      - sns: ${ssm:/sns/${self:service}/${self:provider.stage}/AttendeeLeft_arn~true}
  
  MeetingChangePropagator:
    handler: src/modules/meetings/usecase/meetingChangePropagator/index.handler
    environment:
      MAIN_TABLE_NAME: ${self:custom.mainTableName}
    events:
      - sns: ${ssm:/sns/${self:service}/${self:provider.stage}/MeetingChanged_arn~true}
